# Site settings
title: David George MTG
email: geor0239@algonquinlive.com
description: > # this means to ignore newlines until "baseurl:"
 This is my hobby site for a game I love - Magic The Gathering
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  DavidCGeorge

# Build settings
markdown: kramdown
